### ISSUE TITLE
Enet Windows Binding - Illegal recursion in type

### ISSUE THREAD

**Issue by jasonpeinko** [c0ntribut0r/cat-400#27]
```
C:\Users\jason\.nimble\pkgs\c4-#head\c4\lib\enet\enet.nim(16, 5) Error: illegal recursion in type 'Socket'
```

Corresponding enet.nim lines https://github.com/c0ntribut0r/cat-400/blob/565c3d283096205282e0fd4f44f02afe1d2dfa90/c4/lib/enet/enet.nim#L15-L20

Not needed if switching to netpipe in #26

**Comment by 0xE111** [comment]
7f9b40e0c56f4a1b102bc9b64df0139f7c34e82c should fix this issue. I don't have a working Windows installation, so I cannot test right now.

#26 is not related, it's just an alternative way of doing things for those who aren't happy with external dependency (like enet).

**Comment by jasonpeinko** [comment]
New error. I don't use windows often so its not important to me. Unfortunately i'm not more familiar with nim to debug further. 

```
C:\Users\jason\.nimble\pkgs\c4-#head\c4\lib\enet\enet.nim(23, 20) Error: cannot 'importc' variable at compile time; INVALID_SOCKET
```

**Comment by 0xE111** [comment]
Thanks! Will fix when checking this project on Windows. Leaving open for now.

**Comment by 0xE111** [comment]
Switched to native network library
