### ISSUE TITLE
Not stable dependencines in default Nimble installation

### ISSUE THREAD

**Issue by Toma400** [c0ntribut0r/cat-400#32]
Today, trying to redownload most of libraries for my brand new Nim 2.0 installation, decided to give Cat400 a redownload as well.  
However, I received such message:
```
Downloading https://github.com/c0ntribut0r/cat-400 using git
   Warning: The package has no tagged releases, downloading HEAD instead.
  Verifying dependencies for c4@0.2.2
       Tip: 3 messages have been suppressed, use --verbose to show them.
nimble.nim(107)          processFreeDependencies

    Error:  Unsatisfied dependency: nim (>= 2.1)
```
I assume it may be automatic Nimble generation of Nim version being worked on (indev Nim I think?), but this makes it kinda bad on user side: setting requirement on >= 2.0 Nim is already a bit rough for users who use old Nim considering 2.0 was released roughly a month ago - but putting requirement on indev version makes it extremely awkward, considering most users will rather use stable version.

I'd suggest changing the cap to 2.0 (or lower, if it's possible) to address my concerns. I really hope for it at least, because I was really eager to give Cat400 second try on new installation and would love to do it fairly soon.

**Comment by 0xE111** [comment]
It was indeed a version of Nim used in development. I [lowered the version](https://github.com/c0ntribut0r/cat-400/commit/4bf8dcd20771da7780a280b4f4a178b04d7d820a), but 1) currently there is no guarantee for the framework to work on 2.0 (it was never tested), and 2) the framework is WIP and is not expected to be used yet (even docs are not complete).
Anyway, thanks for the suggestion, it makes sense.
