### ISSUE TITLE
sandbox's collectAssets does not copy gls4 shaders.

### ISSUE THREAD

**Issue by enthus1ast** [c0ntribut0r/cat-400#4]
### Expected behaviour:
What should happen?
collectAssets should copy all required assets into `build` folder. 
Also gls4 shaders.

### Real behaviour:
What happens?
collectAssets does not copy gls4 shaders.

*Nim version:* Nim Compiler Version 0.19.1 [Linux: amd64]

*Framework version:* current

**Comment by 0xE111** [comment]
`collectAssets` should copy assets from sources to build dir. I made it to use absolute path, hope it helps. Please report if problem persists.
